---
name: "test"

on:
  - "push"
  - "pull_request"

jobs:
  test:
    name: "Test on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "windows-latest"
          - "macOS-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "oven-sh/setup-bun@v2"
        with:
          bun-version: "latest"
      - run: "bun install"
      - run: "bun run lint"
      - run: "bun run test"
      - name: "release"
        uses: "softprops/action-gh-release@v2"
        if: github.ref_type == 'tag'
        with:
          draft: true
